import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

/**
 * Loop-boundary guard for the committed README demo clips
 * (`assets/demos/*.svg`, generated by `scripts/demo.mjs` via `domotion-svg`).
 *
 * Each demo types a command (drawn by a domotion `typing` overlay) and then
 * reveals the verbatim CLI output. domotion's typing overlay deliberately
 * self-erases just before the frame ends — it holds the typed text until
 * `frameEnd-150ms`, then fades it out by `frameEnd-50ms` — so the command can't
 * bleed across the loop cut. The output, however, lives in the captured frame
 * HTML, so a plain reveal animation that holds `opacity: 1` to 100% kept the
 * output fully visible through the closing crossfade. The result (PGLM-46) was a
 * jarring tail: for the last ~0.5s of every loop the output sat above an
 * already-cleared `$` prompt, the typed command gone but its output lingering.
 *
 * The fix fades the output back out over that same window (`scripts/demo.mjs`
 * drives the wrapping `.out` opacity 1→0 while `.outbody` carries the reveal, so
 * the two animations don't clash on one node), so the command and its output
 * disappear together and the frame loops from a clean prompt.
 *
 * These are CSS-animation facts we can read straight out of the committed SVG —
 * no browser. The guard asserts that every demo's output is both revealed and
 * then hidden, and that the output disappears no later than the typed command —
 * so the output can never outlive the command at the loop boundary.
 *
 * Scope: the output reveal/hide timeline vs the command-text lifetime. The
 * caret/typing fidelity is covered separately in `demo-caret.test.ts`.
 */

const DEMOS = ['app-driven', 'dry-run', 'standalone', 'safety'] as const;

/** Tolerance (in timeline %) for "same instant" — ~0.4% of a ~7.7s scene ≈ 30ms. */
const SAME_INSTANT_PCT = 0.4;

interface KeyframeGroup {
  stops: number[];
  value: number;
}

/** Depth-aware body of `@keyframes <name>{ … }` (handles nested `{}`). */
function keyframesBody(css: string, name: string): string | undefined {
  const key = `@keyframes ${name}{`;
  const start = css.indexOf(key);
  if (start === -1) return undefined;
  let depth = 1;
  let i = start + key.length;
  for (; depth > 0 && i < css.length; i++) {
    if (css[i] === '{') depth++;
    else if (css[i] === '}') depth--;
  }
  return css.slice(start + key.length, i - 1);
}

/**
 * Parse an opacity keyframe body into its stop groups, e.g.
 * `0%,48.166%{opacity:0}52.054%,to{opacity:1}` →
 * `[{stops:[0,48.166], value:0}, {stops:[52.054,100], value:1}]`.
 */
function parseOpacityGroups(body: string): KeyframeGroup[] {
  const groups: KeyframeGroup[] = [];
  const re = /([0-9.,%a-z\s]+?)\{([^}]*)\}/g;
  for (let m = re.exec(body); m !== null; m = re.exec(body)) {
    const [, selRaw, decl] = m;
    const opacity = /opacity:\s*(-?\d+(?:\.\d+)?)/.exec(decl);
    if (!opacity) continue;
    const stops = selRaw
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .map((s) => (s === 'from' ? 0 : s === 'to' ? 100 : Number.parseFloat(s)))
      .filter((n) => Number.isFinite(n));
    groups.push({ stops, value: Number(opacity[1]) });
  }
  return groups;
}

/** The opacity value at a given timeline %, reading the group whose stops bracket it. */
function valueAtPct(groups: KeyframeGroup[], at: number): number {
  const exact = groups.find((g) => g.stops.includes(at));
  return (exact ?? groups[0]).value;
}

/** Every intra-frame opacity keyframe (`f<frame>-<animId>-<i>`) with its parsed groups. */
function intraFrameOpacityKeyframes(css: string): { name: string; groups: KeyframeGroup[] }[] {
  const out: { name: string; groups: KeyframeGroup[] }[] = [];
  const re = /@keyframes (f\d+-[a-z0-9]+-\d+)\{/g;
  for (let m = re.exec(css); m !== null; m = re.exec(css)) {
    const body = keyframesBody(css, m[1]);
    if (body === undefined || !/opacity/.test(body)) continue;
    out.push({ name: m[1], groups: parseOpacityGroups(body) });
  }
  return out;
}

/** The % at which the typed command text fully disappears (its `t<line>-vis` keyframe). */
function commandGonePct(css: string, line = 1): number {
  const groups = parseOpacityGroups(keyframesBody(css, `t${line.toString()}-vis`) ?? '');
  const visible = groups.find((g) => g.value === 1);
  const hidden = groups.find((g) => g.value === 0);
  if (!visible || !hidden) throw new Error('no two-state command-text vis keyframe');
  const lastVisible = Math.max(...visible.stops);
  // The command is gone at the first hidden stop after it was last visible.
  return Math.min(...hidden.stops.filter((s) => s > lastVisible));
}

describe('assets/demos output never outlives the typed command at the loop (PGLM-46)', () => {
  for (const name of DEMOS) {
    describe(`${name}.svg`, () => {
      const css = readFileSync(new URL(`../assets/demos/${name}.svg`, import.meta.url), 'utf8');
      const kfs = intraFrameOpacityKeyframes(css);
      // Reveal: opacity 0 at the start, 1 at the loop end (output appears, held).
      const reveal = kfs.find((k) => valueAtPct(k.groups, 0) === 0 && valueAtPct(k.groups, 100) === 1);
      // Hide: opacity 1 at the start, 0 at the loop end (output cleared before looping).
      const hide = kfs.find((k) => valueAtPct(k.groups, 0) === 1 && valueAtPct(k.groups, 100) === 0);

      it('reveals the output (opacity 0 → 1)', () => {
        expect(reveal, 'an output reveal keyframe').toBeDefined();
      });

      // The exact PGLM-46 guard: the output used to hold opacity 1 to 100% (no
      // hide), so it stayed visible through the loop crossfade after the typed
      // command had already self-erased. Require the output to be faded back out.
      it('hides the output again before the loop (opacity 1 → 0)', () => {
        expect(hide, 'an output hide keyframe — the output must clear before looping').toBeDefined();
      });

      it('clears the output no later than the typed command disappears', () => {
        const hidden = hide!.groups.find((g) => g.value === 0)!;
        const stillVisible = hide!.groups.find((g) => g.value === 1)!;
        const outputGone = Math.min(...hidden.stops.filter((s) => s > Math.max(...stillVisible.stops)));
        const cmdGone = commandGonePct(css);
        // Output must vanish at (or before) the command — never linger past it.
        expect(outputGone).toBeLessThanOrEqual(cmdGone + SAME_INSTANT_PCT);
      });

      it('keeps the output visible long enough to read (reveal completes before the hide starts)', () => {
        const revealedAt = Math.min(...reveal!.groups.find((g) => g.value === 1)!.stops);
        const hideStartsAt = Math.max(...hide!.groups.find((g) => g.value === 1)!.stops);
        expect(revealedAt).toBeLessThan(hideStartsAt);
      });
    });
  }
});

describe('opacity keyframe parser', () => {
  it('parses a reveal keyframe (0 → 1) into bracketing stop groups', () => {
    const groups = parseOpacityGroups('0%,48.166%{opacity:0}52.054%,to{opacity:1}');
    expect(valueAtPct(groups, 0)).toBe(0);
    expect(valueAtPct(groups, 100)).toBe(1);
  });

  it('parses a hide keyframe (1 → 0) and reads its loop-end value', () => {
    const groups = parseOpacityGroups('0%,91.577%{opacity:1}92.873%,to{opacity:0}');
    expect(valueAtPct(groups, 0)).toBe(1);
    expect(valueAtPct(groups, 100)).toBe(0);
  });

  it('reads when the command text disappears from its vis keyframe', () => {
    const css = '@keyframes t1-vis{0%,31.1%,92.87%,to{opacity:0}31.49%,91.58%{opacity:1}}';
    expect(commandGonePct(css)).toBeCloseTo(92.87, 2);
  });
});
