import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

/**
 * Caret-tracking guard for the committed README demo clips
 * (`assets/demos/*.svg`, generated by `scripts/demo.mjs` via `domotion-svg`).
 *
 * The demos type a command with a blinking caret, then reveal the verbatim CLI
 * output. A domotion bug (DM-1204, surfaced here as PGLM-37) let the caret trail
 * the typed text by ~10–20 chars mid-line. Both the text-reveal clip
 * (`.t{N}-rev{M}`) and the caret position track (`.t{N}-caret` → `*-caret-pos`)
 * shared the *same* keyframe window, but the reveal animation shipped with **no
 * timing function** — so it defaulted to `ease` — while the caret used `linear`.
 * Over an identical window, an eased reveal edge accelerates through the middle
 * and runs ahead of the constant-speed caret, then the two meet again at the
 * ends. That is exactly the reported symptom: parked end-state correct, mid-type
 * lag. domotion 0.13.1 fixed it by emitting `linear` on the reveal so both ramp
 * at a constant rate and the caret tracks the reveal edge at every instant.
 *
 * These are CSS-animation facts we can read straight out of the committed SVG —
 * no browser. The primary guard asserts the reveal and caret-position share a
 * timing function (the exact thing DM-1204 broke); two secondary guards assert
 * they also share the ramp window and the caret parks at the text edge.
 *
 * Scope: the typing/caret timeline only. Glyph layout is domotion's concern.
 */

const DEMOS = ['app-driven', 'dry-run', 'standalone', 'safety'] as const;

/** Longest-first so `ease-in-out` wins over `ease-in`/`ease` during matching. */
const TIMING_KEYWORDS = [
  'ease-in-out',
  'ease-in',
  'ease-out',
  'cubic-bezier',
  'step-start',
  'step-end',
  'steps',
  'linear',
  'ease',
] as const;

/**
 * The `animation-timing-function` of a single `animation` shorthand value, e.g.
 * `t1-rev0 7.72s linear infinite` → `linear`. CSS defaults an omitted timing
 * function to `ease` — which is the DM-1204 bug, so we must return that default
 * rather than guess `linear`.
 */
function timingFunction(animationValue: string): string {
  for (const kw of TIMING_KEYWORDS) {
    if (new RegExp(`(^|[\\s,(])${kw}\\b`).test(animationValue)) return kw;
  }
  return 'ease';
}

/** Body of a CSS rule `<selector>{ … }` (selector is a literal string, not a regex). */
function ruleBody(css: string, selector: string): string | undefined {
  const key = `${selector}{`;
  const start = css.indexOf(key);
  if (start === -1) return undefined;
  const end = css.indexOf('}', start);
  return css.slice(start + key.length, end);
}

/** The `animation:` value of a class rule, e.g. `.t1-rev0` → `t1-rev0 7.72s linear infinite`. */
function animationValue(css: string, selector: string): string | undefined {
  const body = ruleBody(css, selector);
  const m = body !== undefined ? /animation:\s*([^;]*)/.exec(body) : null;
  return m ? m[1].trim() : undefined;
}

/** The comma-segment of an animation list that drives a given keyframe name. */
function segmentFor(animationList: string, keyframeName: string): string | undefined {
  return animationList.split(',').find((seg) => new RegExp(`\\b${keyframeName}\\b`).test(seg));
}

interface Ramp {
  rampStart: number;
  rampEnd: number;
  /** Active value (px): reveal width, or caret end translateX. */
  value: number;
}

function keyframesBody(css: string, name: string): string | undefined {
  const key = `@keyframes ${name}{`;
  const start = css.indexOf(key);
  if (start === -1) return undefined;
  let depth = 1;
  let i = start + key.length;
  for (; depth > 0 && i < css.length; i++) {
    if (css[i] === '{') depth++;
    else if (css[i] === '}') depth--;
  }
  return css.slice(start + key.length, i - 1);
}

/** Parse a two-state ramp keyframe (rest = 0, active = V) into its forward ramp window. */
function parseRamp(body: string): Ramp {
  const groups: { stops: number[]; value: number }[] = [];
  const re = /([0-9.,%a-z\s]+?)\{([^}]*)\}/g;
  for (let m = re.exec(body); m !== null; m = re.exec(body)) {
    const [, selRaw, decl] = m;
    const stops = selRaw
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .map((s) => (s === 'from' ? 0 : s === 'to' ? 100 : Number.parseFloat(s)));
    const numMatch = /-?\d+(?:\.\d+)?/.exec(decl.replace(/^[^:]*:/, ''));
    groups.push({ stops, value: numMatch ? Math.abs(Number(numMatch[0])) : 0 });
  }
  const active = groups.find((g) => g.value > 0);
  const rest = groups.find((g) => g.value === 0);
  if (!active || !rest) throw new Error(`not a two-state ramp keyframe: ${body}`);
  const rampEnd = Math.min(...active.stops);
  const rampStart = Math.max(...rest.stops.filter((s) => s < rampEnd));
  return { rampStart, rampEnd, value: active.value };
}

function caretLines(css: string): number[] {
  const lines = new Set<number>();
  const re = /@keyframes t(\d+)-caret-pos\{/g;
  for (let m = re.exec(css); m !== null; m = re.exec(css)) lines.add(Number(m[1]));
  return [...lines].sort((a, b) => a - b);
}

function revealSegments(css: string, line: number): Ramp[] {
  const segments: Ramp[] = [];
  for (let m = 0; ; m++) {
    const body = keyframesBody(css, `t${line.toString()}-rev${m.toString()}`);
    if (body === undefined) break;
    segments.push(parseRamp(body));
  }
  return segments;
}

describe('assets/demos caret tracks the typed text (PGLM-37 / DM-1204)', () => {
  for (const name of DEMOS) {
    describe(`${name}.svg`, () => {
      const css = readFileSync(new URL(`../assets/demos/${name}.svg`, import.meta.url), 'utf8');
      const lines = caretLines(css);

      it('has a typed line with a caret and a matching reveal', () => {
        expect(lines.length).toBeGreaterThanOrEqual(1);
        for (const line of lines) {
          expect(revealSegments(css, line).length).toBeGreaterThanOrEqual(1);
          expect(animationValue(css, `.t${line.toString()}-caret`)).toBeDefined();
          expect(animationValue(css, `.t${line.toString()}-rev0`)).toBeDefined();
        }
      });

      // The exact DM-1204 guard: the reveal eased (default) while the caret was
      // linear, so the reveal edge ran ahead mid-type. Require both to use the
      // same constant-speed timing so the caret can never lag the reveal edge.
      it('drives the reveal and the caret with the same constant-speed timing', () => {
        for (const line of lines) {
          const caretList = animationValue(css, `.t${line.toString()}-caret`)!;
          const caretSeg = segmentFor(caretList, `t${line.toString()}-caret-pos`)!;
          const caretTiming = timingFunction(caretSeg);

          for (let m = 0; m < revealSegments(css, line).length; m++) {
            const revList = animationValue(css, `.t${line.toString()}-rev${m.toString()}`)!;
            const revTiming = timingFunction(revList);
            expect(revTiming).toBe(caretTiming);
            expect(revTiming).toBe('linear');
          }
        }
      });

      it('ramps the caret over the same keyframe window as the reveal', () => {
        for (const line of lines) {
          const caret = parseRamp(keyframesBody(css, `t${line.toString()}-caret-pos`)!);
          const reveals = revealSegments(css, line);
          expect(caret.rampStart).toBeCloseTo(Math.min(...reveals.map((r) => r.rampStart)), 1);
          expect(caret.rampEnd).toBeCloseTo(Math.max(...reveals.map((r) => r.rampEnd)), 1);
        }
      });

      it('parks the caret at the text edge (within one trailing char, never behind/ahead)', () => {
        for (const line of lines) {
          const caret = parseRamp(keyframesBody(css, `t${line.toString()}-caret-pos`)!);
          const fullWidth = Math.max(...revealSegments(css, line).map((r) => r.value));
          const behind = fullWidth - caret.value;
          // The demo appends a trailing space, so the caret parks ~1 char (≈9px)
          // behind the full reveal width. Guard a 2-char band; reject sitting far
          // behind (the DM-1204 symptom) or ahead of the text.
          expect(behind).toBeGreaterThanOrEqual(0);
          expect(behind).toBeLessThanOrEqual(20);
        }
      });
    });
  }
});

describe('animation timing-function parser', () => {
  it('reads the timing function from an animation shorthand', () => {
    expect(timingFunction('t1-rev0 7.72s linear infinite')).toBe('linear');
    expect(timingFunction('t1-caret-pos 7.72s linear infinite')).toBe('linear');
    expect(timingFunction('x 1s ease-in-out infinite')).toBe('ease-in-out');
    expect(timingFunction('x 1s step-end infinite')).toBe('step-end');
  });

  it('defaults an omitted timing function to ease (the DM-1204 reveal)', () => {
    // The buggy reveal shipped as `t1-rev0 7.72s infinite` — no timing token.
    expect(timingFunction('t1-rev0 7.72s infinite')).toBe('ease');
  });

  it('flags the DM-1204 mismatch: eased reveal vs linear caret', () => {
    const revTiming = timingFunction('t1-rev0 7.72s infinite'); // pre-fix reveal
    const caretTiming = timingFunction('t1-caret-pos 7.72s linear infinite');
    expect(revTiming).toBe('ease');
    expect(caretTiming).toBe('linear');
    expect(revTiming).not.toBe(caretTiming); // the guard above would fail on this pair
  });
});
