import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

/**
 * Layout guard for the committed README architecture diagram
 * (`assets/diagram.svg`, generated by `scripts/diagram.mjs`).
 *
 * The diagram is authored as HTML/CSS and captured to SVG with `domotion-svg`.
 * A layout regression once let the center "introspect → topo-sort" label crowd
 * the arrow line / `COPY (text)` pill (PGLM-36). domotion emits every text run
 * as `<g role="img" aria-label="…"><text x="…" y="…" font-size="…">`, so we can
 * parse the run geometry straight out of the committed SVG — no browser — and
 * assert the rows can't be colliding. Regenerating the diagram with crowded
 * rows fails this test.
 *
 * Scope: the static diagram only. The demo clips under `assets/demos/` are
 * multi-frame animated SVGs whose runs legitimately share coordinates across
 * frames, so the same parse does not apply to them.
 */

interface TextRun {
  label: string;
  /** Baseline Y (px) of the run. */
  baseline: number;
  fontSize: number;
  /** Approximate horizontal extent of the run (px). */
  x0: number;
  x1: number;
  /** Approximate vertical extent of the glyphs (px): cap height to descender. */
  top: number;
  bottom: number;
}

/** Pull every aria-labelled text run, with an approximate bounding box, from a domotion SVG. */
function parseTextRuns(svg: string): TextRun[] {
  const re =
    /<g role="img" aria-label="([^"]*)"><title>[^<]*<\/title><text x="([^"]+)" y="([\d.]+)"[^>]*?font-size="([\d.]+)"/g;
  const runs: TextRun[] = [];
  for (let m = re.exec(svg); m !== null; m = re.exec(svg)) {
    const [, label, xs, yStr, fsStr] = m;
    const xList = xs.trim().split(/\s+/).map(Number);
    const fontSize = Number(fsStr);
    const baseline = Number(yStr);
    runs.push({
      label,
      baseline,
      fontSize,
      x0: Math.min(...xList),
      // The x list is per-glyph origins; the last glyph extends ~0.6em past its origin.
      x1: Math.max(...xList) + fontSize * 0.6,
      top: baseline - fontSize * 0.78, // cap height above the baseline
      bottom: baseline + fontSize * 0.25, // descender below the baseline
    });
  }
  return runs;
}

/** Do two 1-D ranges overlap by more than `pad`? */
function rangesOverlap(a0: number, a1: number, b0: number, b1: number, pad = 0): boolean {
  return a0 < b1 - pad && b0 < a1 - pad;
}

function findRun(runs: TextRun[], prefix: string): TextRun {
  const run = runs.find((r) => r.label.startsWith(prefix));
  if (!run) throw new Error(`no text run starting with ${JSON.stringify(prefix)} in diagram.svg`);
  return run;
}

const SVG = readFileSync(new URL('../assets/diagram.svg', import.meta.url), 'utf8');

describe('assets/diagram.svg layout', () => {
  const runs = parseTextRuns(SVG);

  it('parses the expected set of labelled text runs', () => {
    expect(runs.length).toBeGreaterThanOrEqual(9);
    for (const label of ['introspect', 'COPY', 'realign', 'old PGlite', 'new PGlite']) {
      expect(runs.some((r) => r.label.startsWith(label))).toBe(true);
    }
  });

  it('stacks the center flow labels with a full line of clearance (no crowding the arrow)', () => {
    // top label, the COPY pill on the arrow line, then the bottom label.
    const rows = [findRun(runs, 'introspect'), findRun(runs, 'COPY'), findRun(runs, 'realign')];

    // Strictly top-to-bottom order.
    expect(rows[0].baseline).toBeLessThan(rows[1].baseline);
    expect(rows[1].baseline).toBeLessThan(rows[2].baseline);

    // Each adjacent pair is separated by at least a full em of both rows — enough
    // room for the arrow line + pill between them. This is what PGLM-36 violated:
    // the crowded layout had a top→pill gap of ~16px (< 24px) and read as overlap.
    for (const [a, b] of [
      [rows[0], rows[1]],
      [rows[1], rows[2]],
    ]) {
      const gap = b.baseline - a.baseline;
      expect(gap).toBeGreaterThanOrEqual(a.fontSize + b.fontSize);
    }
  });

  it('has no two text runs overlapping (no visual collision)', () => {
    const collisions: string[] = [];
    for (let i = 0; i < runs.length; i++) {
      for (let j = i + 1; j < runs.length; j++) {
        const a = runs[i];
        const b = runs[j];
        if (
          rangesOverlap(a.x0, a.x1, b.x0, b.x1, 2) &&
          rangesOverlap(a.top, a.bottom, b.top, b.bottom, 1)
        ) {
          collisions.push(`${JSON.stringify(a.label)} ↔ ${JSON.stringify(b.label)}`);
        }
      }
    }
    expect(collisions).toEqual([]);
  });
});

describe('overlap geometry helpers', () => {
  it('rangesOverlap detects a real overlap and clears a gap', () => {
    expect(rangesOverlap(0, 10, 5, 15)).toBe(true); // overlapping
    expect(rangesOverlap(0, 10, 10, 20)).toBe(false); // touching, no overlap
    expect(rangesOverlap(0, 10, 12, 20)).toBe(false); // clear gap
  });

  it('flags two crowded text rows the way the PGLM-36 regression looked', () => {
    // Synthetic: a 12px label whose baseline sits only ~13px above a pill row —
    // their glyph bands overlap, which is exactly the collision class guarded above.
    const a: TextRun = { label: 'top', baseline: 96, fontSize: 12, x0: 360, x1: 530, top: 86.6, bottom: 99 };
    const b: TextRun = { label: 'pill', baseline: 109, fontSize: 12, x0: 400, x1: 490, top: 99.6, bottom: 112 };
    const collide =
      rangesOverlap(a.x0, a.x1, b.x0, b.x1) && rangesOverlap(a.top, a.bottom, b.top, b.bottom);
    // Bands [86.6,99] and [99.6,112] just clear; but the baseline gap (13px) is
    // far under fontSize+fontSize (24px), which the clearance rule rejects.
    expect(collide).toBe(false);
    expect(b.baseline - a.baseline).toBeLessThan(a.fontSize + b.fontSize);
  });
});
